"""Turns data/cases.json into prototype/js/cases-data.js (a plain script, so the app also works from file://
and inside the single-file build). Run after scripts/fetch_data.py."""
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
cases = json.loads((root / 'data' / 'cases.json').read_text(encoding='utf-8'))
rows = []
for c in cases:
    cs = ','.join('["%s",%s,%s,%s,%s,%d]' % (x['d'], x['o'], x['h'], x['l'], x['c'], x['v']) for x in c['candles'])
    rows.append('{id:%d,ticker:%s,di:%d,c:[%s]}' % (c['id'], json.dumps(c['ticker']), c['decisionIndex'], cs))
out = ("/* generated by scripts/make_cases_js.py from data/cases.json. Real historical daily data (Yahoo Finance via yfinance).\n"
       "   Private testing only, not for distribution. Row: [date, open, high, low, close, volume]. */\n"
       "const REAL_CASES = [\n" + ',\n'.join(rows) + '\n];\n')
(root / 'prototype' / 'js' / 'cases-data.js').write_text(out, encoding='utf-8')
print('wrote cases-data.js', len(out) // 1024, 'KB')
