'use strict';
/* ===== professional data-art: annotated charts and diagrams, hand-built SVG (nothing external) ===== */
let _u = 0; const uid = () => 'a' + (_u++);
const GR = '#1ff0b0', RD = '#ff6048', GD = '#ffc94d', BL = '#6aa8ff', VI = '#a78bfa', MUT = '#8b93a1';
const T = (x, y, t, fill = '#fff', size = 11, w = 600, anchor = 'middle') => `<text x="${x}" y="${y}" fill="${fill}" font-size="${size}" font-weight="${w}" text-anchor="${anchor}" font-family="Heebo,sans-serif">${t}</text>`;
const pill = (x, y, text, col = GR, tc) => { const w = Math.max(36, text.length * 6.4 + 18); return `<g><rect x="${x - w / 2}" y="${y - 10}" width="${w}" height="20" rx="10" fill="${col}" fill-opacity=".16" stroke="${col}" stroke-opacity=".75"/>${T(x, y + 4, text, tc || col, 11, 700)}</g>`; };
const bgS = (a = '#0d1424', b = '#18223d') => { const id = uid(), g = uid(); return `<defs><linearGradient id="${id}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient><radialGradient id="${g}" cx=".85" cy=".1" r=".7"><stop offset="0" stop-color="${GR}" stop-opacity=".16"/><stop offset="1" stop-color="${GR}" stop-opacity="0"/></radialGradient></defs><rect width="320" height="200" fill="url(#${id})"/><rect width="320" height="200" fill="url(#${g})"/><g stroke="#fff" stroke-opacity=".05">${[40, 80, 120, 160].map(y => `<path d="M0 ${y}H320"/>`).join('')}${[64, 128, 192, 256].map(x => `<path d="M${x} 0V200"/>`).join('')}</g>`; };
function genC(seed, n, start, drift, vol) { const r = rng(seed); let p = start; const out = []; for (let i = 0; i < n; i++) { const o = p, c = o + drift + (r() - .5) * vol * 2; out.push({ o, c, h: Math.max(o, c) + r() * vol * .7, l: Math.min(o, c) - r() * vol * .7 }); p = c; } return out; }
function fromCloses(cl, w = .5, lowAt = {}, highAt = {}) { return cl.map((c, i) => { const o = i ? cl[i - 1] : c - .6, h = highAt[i] != null ? highAt[i] : Math.max(o, c) + w, l = lowAt[i] != null ? lowAt[i] : Math.min(o, c) - w; return { o, c, h, l }; }); }
/* draws candles scaled into a box; returns svg + coordinate helpers */
function chartBox(arr, x0, x1, y0, y1, o = {}) {
  const hi = Math.max(...arr.map(c => c.h)), lo = Math.min(...arr.map(c => c.l)), n = arr.length, slot = (x1 - x0) / n, bw = Math.min(14, slot * .62);
  const X = (i) => x0 + slot * (i + .5), Y = (v) => y1 - (v - lo) / (hi - lo || 1) * (y1 - y0);
  const svg = arr.map((c, i) => { const up = c.c >= c.o, col = up ? GR : RD; return `<g class="cn" style="animation-delay:${(o.delay || 0) + i * 35}ms"><line x1="${X(i)}" x2="${X(i)}" y1="${Y(c.h)}" y2="${Y(c.l)}" stroke="${col}" stroke-width="1.6" stroke-linecap="round"/><rect x="${X(i) - bw / 2}" y="${Y(Math.max(c.o, c.c))}" width="${bw}" height="${Math.max(2, Math.abs(Y(c.o) - Y(c.c)))}" rx="2" fill="${col}"/></g>`; }).join('');
  return { svg, X, Y, lo, hi };
}
const dash = (x1, y1, x2, y2, col, w = 1.6) => `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${col}" stroke-width="${w}" stroke-dasharray="5 5" class="flow"/>`;
const dot = (x, y, col, r = 4.5) => `<circle cx="${x}" cy="${y}" r="${r + 5}" fill="${col}" fill-opacity=".2" class="pulse-r"/><circle cx="${x}" cy="${y}" r="${r}" fill="${col}" stroke="#0d1424" stroke-width="2"/>`;
const argmin = (a, f, t, k = 'l') => { let b = f; for (let i = f; i < t; i++) if (a[i][k] < a[b][k]) b = i; return b; };
const argmax = (a, f, t, k = 'h') => { let b = f; for (let i = f; i < t; i++) if (a[i][k] > a[b][k]) b = i; return b; };

const SCENES = {
  pie: () => bgS() + `<g><rect x="22" y="36" width="116" height="128" rx="16" fill="#fff" fill-opacity=".05" stroke="#fff" stroke-opacity=".14"/><g fill="none" stroke="${BL}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M50 128V84l22-10 22 10v44"/><path d="M42 128h60M60 98h8M76 98h8M60 112h8M76 112h8"/></g>${T(80, 150, 'החברה', '#fff', 13, 700)}</g>` +
    `<g transform="translate(228 100)"><circle r="50" fill="none" stroke="#fff" stroke-opacity=".12" stroke-width="16"/><circle r="50" fill="none" stroke="${GR}" stroke-width="16" stroke-dasharray="70 314" transform="rotate(-90)" stroke-linecap="butt" class="seg"/>${T(0, 5, 'המניה שלך', '#fff', 12, 700)}</g>` + dash(140, 100, 176, 100, GR) + pill(228, 172, 'חלק קטן מהחברה', GR),
  market: () => bgS() + (() => { const B = [78, 66, 54, 42, 32, 22, 14], S = [20, 30, 40, 52, 62, 74, 84]; let s = ''; B.forEach((w, i) => { const y = 54 + i * 17; s += `<rect x="${158 - w * 1.75}" y="${y}" width="${w * 1.75}" height="11" rx="5" fill="${GR}" fill-opacity="${.85 - i * .08}" class="bar" style="animation-delay:${i * 70}ms;transform-origin:158px ${y}px"/><rect x="162" y="${y}" width="${S[i] * 1.75}" height="11" rx="5" fill="${RD}" fill-opacity="${.3 + i * .09}" class="bar" style="animation-delay:${i * 70}ms;transform-origin:162px ${y}px"/>`; }); return s; })() + `<path d="M160 44V176" stroke="#fff" stroke-opacity=".5" stroke-dasharray="3 4"/>` + pill(86, 30, 'קונים', GR) + pill(234, 30, 'מוכרים', RD) + pill(160, 188, 'מחיר 100', '#fff', '#fff'),
  riskline: () => { const a = genC(11, 30, 100, .4, 3.2), c = chartBox(a, 24, 296, 40, 168); const pts = a.map((k, i) => `${c.X(i).toFixed(1)},${c.Y(k.c).toFixed(1)}`); const dip = argmin(a, 8, 24, 'c'); const id = uid(); return bgS() + `<defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${GR}" stop-opacity=".35"/><stop offset="1" stop-color="${GR}" stop-opacity="0"/></linearGradient></defs><path d="M${pts.join(' L')} L296,176 L24,176Z" fill="url(#${id})"/><path d="M${pts.join(' L')}" fill="none" stroke="${GR}" stroke-width="2.6" stroke-linejoin="round" class="draw" style="filter:drop-shadow(0 0 6px ${GR})"/>` + `<rect x="${c.X(dip) - 26}" y="40" width="52" height="136" rx="8" fill="${RD}" fill-opacity=".1"/>` + dot(c.X(dip), c.Y(a[dip].c), RD) + pill(Math.min(c.X(dip), 200), 28, 'אפשר להפסיד', RD) + dot(c.X(29), c.Y(a[29].c), GR); },
  styles: () => bgS() + [['טווח ארוך', 'שנים', 26, 272, GR], ['סווינג', 'שבועות', 80, 150, BL], ['יומי', 'שעות', 134, 64, GD]].map(([t, u, y, w, col], i) => `<g>${T(24, y, t, '#fff', 12.5, 700, 'start')}${T(296, y, u, MUT, 11, 600, 'end')}<rect x="24" y="${y + 8}" width="272" height="16" rx="8" fill="#fff" fill-opacity=".07"/><rect x="24" y="${y + 8}" width="${w}" height="16" rx="8" fill="${col}" class="bar" style="animation-delay:${i * 150}ms;transform-origin:24px ${y}px"/></g>`).join('') + T(160, 188, 'כמה זמן מחזיקים בעסקה', MUT, 10.5),
  candle1: () => bgS() + `<g><line x1="108" x2="108" y1="24" y2="178" stroke="${GR}" stroke-width="4" stroke-linecap="round"/><rect x="86" y="62" width="44" height="86" rx="7" fill="${GR}"/><rect x="86" y="62" width="44" height="12" rx="6" fill="#fff" fill-opacity=".25"/></g>` +
    [['הכי גבוה', 24], ['סגירה', 62], ['פתיחה', 148], ['הכי נמוך', 178]].map(([t, yy]) => dash(134, yy, 196, yy, '#fff', 1) + pill(246, yy, t, '#fff', '#fff')).join('') + `<path d="M68 148V62" stroke="${GR}" stroke-width="1.4"/><path d="M63 70l5 -8 5 8" fill="none" stroke="${GR}" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>` + T(52, 108, 'עלה', GR, 11, 700),
  candle2: () => bgS() + `<g><line x1="100" x2="100" y1="34" y2="172" stroke="${GR}" stroke-width="4" stroke-linecap="round"/><rect x="80" y="66" width="40" height="76" rx="7" fill="${GR}"/></g><g><line x1="220" x2="220" y1="28" y2="166" stroke="${RD}" stroke-width="4" stroke-linecap="round"/><rect x="200" y="58" width="40" height="78" rx="7" fill="${RD}"/></g>` + pill(100, 186, 'סגירה גבוהה', GR) + pill(220, 186, 'סגירה נמוכה', RD) + `<path d="M100 142V66M95 74l5 -8 5 8" fill="none" stroke="#06201a" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M220 58v78M215 128l5 8 5 -8" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>`,
  index: () => bgS() + (() => { const tiles = [[24, 60, 104, 108, '#3b82f6'], [132, 60, 66, 70, '#8b5cf6'], [132, 134, 66, 34, '#14b8a6'], [202, 60, 94, 50, '#f59e0b'], [202, 114, 46, 54, '#ec4899'], [252, 114, 44, 54, '#22c55e']]; return tiles.map(([x, y, w, h, c], i) => `<g class="bar" style="animation-delay:${i * 80}ms;transform-origin:${x}px ${y + h}px"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="9" fill="${c}" fill-opacity=".85"/><path d="M${x + 8} ${y + h - 10}l${w / 4} -${h / 5}l${w / 4} ${h / 8}l${w / 3} -${h / 3}" fill="none" stroke="#fff" stroke-opacity=".8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></g>`).join(''); })() + `<path d="M24 46h272" stroke="${GR}" stroke-width="3" stroke-linecap="round"/>` + pill(160, 28, 'מדד = ממוצע של כל החברות', GR),
  volume: () => { const a = genC(21, 22, 100, .5, 3), c = chartBox(a, 24, 296, 30, 126); const vs = a.map((k, i) => 14 + Math.abs(k.c - k.o) * 9 + (i % 4) * 5); return bgS() + c.svg + vs.map((v, i) => `<rect x="${c.X(i) - 5}" y="${180 - v}" width="10" height="${v}" rx="2" fill="${a[i].c >= a[i].o ? GR : RD}" fill-opacity=".7" class="bar" style="animation-delay:${i * 30}ms;transform-origin:${c.X(i)}px 180px"/>`).join('') + pill(44, 30, 'נפח', '#fff', '#fff') + `<path d="M24 138h272" stroke="#fff" stroke-opacity=".15"/>`; },
  ma: () => { const a = genC(31, 28, 100, .45, 3.4), c = chartBox(a, 24, 296, 30, 170); const m = a.map((_, i) => { const s = a.slice(Math.max(0, i - 6), i + 1); return s.reduce((x, k) => x + k.c, 0) / s.length; }); const d = m.map((v, i) => `${i ? 'L' : 'M'}${c.X(i).toFixed(1)},${c.Y(v).toFixed(1)}`).join(' '); return bgS() + c.svg.replace(/stroke-width="1.6"/g, 'stroke-width="1.2"').replace(/fill="#1ff0b0"/g, 'fill="#1ff0b0" fill-opacity=".45"').replace(/fill="#ff6048"/g, 'fill="#ff6048" fill-opacity=".45"') + `<path d="${d}" fill="none" stroke="${GD}" stroke-width="3" stroke-linecap="round" class="draw" style="filter:drop-shadow(0 0 6px ${GD})"/>` + pill(160, 188, 'הקו הצהוב מחליק את הקפיצות', GD) + dot(c.X(27), c.Y(m[27]), GD, 4); },
  trendUp: () => { const a = genC(41, 24, 100, 1.2, 2.2), c = chartBox(a, 24, 296, 26, 168); const l = [argmin(a, 1, 8), argmin(a, 8, 16), argmin(a, 16, 24)]; return bgS() + c.svg + dash(c.X(l[0]), c.Y(a[l[0]].l), c.X(l[2]), c.Y(a[l[2]].l), GD, 2) + l.map(i => dot(c.X(i), c.Y(a[i].l), GD, 3.6)).join('') + pill(160, 188, 'כל נקודה נמוכה גבוהה מהקודמת', GD); },
  trendDown: () => { const a = genC(51, 24, 130, -1.2, 2.2), c = chartBox(a, 24, 296, 26, 172); const h = [argmax(a, 1, 8), argmax(a, 8, 16), argmax(a, 16, 24)]; return bgS() + c.svg + dash(c.X(h[0]), c.Y(a[h[0]].h), c.X(h[2]), c.Y(a[h[2]].h), GD, 2) + h.map(i => dot(c.X(i), c.Y(a[i].h), GD, 3.6)).join('') + pill(160, 188, 'כל נקודה גבוהה נמוכה מהקודמת', GD); },
  trendSide: () => { const cl = Array.from({ length: 24 }, (_, i) => 100 + Math.sin(i * .85) * 4.2 + ((i * 7) % 3 - 1) * .5), a = fromCloses(cl, .7), c = chartBox(a, 24, 296, 26, 164); return bgS() + `<rect x="24" y="${c.Y(105) - 4}" width="272" height="${c.Y(95.5) - c.Y(105) + 8}" rx="10" fill="${MUT}" fill-opacity=".1" stroke="${MUT}" stroke-opacity=".5" stroke-dasharray="5 5"/>` + c.svg + pill(160, 188, 'קופץ באותו טווח, בלי כיוון', MUT, '#c9cfd8'); },
  support: () => { const cl = [106, 104.5, 102.4, 101, 103, 105.4, 107, 106, 104, 102, 100.8, 102.8, 105, 106.8, 105.2, 103.2, 101.4, 101, 103, 105.8, 107, 106.2], lows = { 3: 99.9, 10: 99.8, 17: 99.9 }, a = fromCloses(cl, .5, lows), c = chartBox(a, 24, 296, 32, 148), t = [3, 10, 17], zy = c.Y(99.9); return bgS() + `<rect x="24" y="${zy - 8}" width="272" height="20" rx="6" fill="${GD}" fill-opacity=".16" stroke="${GD}" stroke-opacity=".6" stroke-dasharray="5 4"/>` + c.svg + t.map((i, k) => dot(c.X(i), c.Y(99.9), GD, 3.8) + T(c.X(i), c.Y(99.9) + 28, String(k + 1), GD, 11, 800)).join('') + pill(160, 188, 'תמיכה: המחיר עצר באזור הזה 3 פעמים', GD); },
  resist: () => { const cl = [94, 95.5, 97.6, 99, 97, 94.6, 93, 94, 96, 98, 99.2, 97.2, 95, 93.2, 94.8, 96.8, 98.6, 99, 97, 94.2, 93, 93.8], highs = { 3: 100.1, 10: 100.2, 17: 100.1 }, a = fromCloses(cl, .5, {}, highs), c = chartBox(a, 24, 296, 44, 160), t = [3, 10, 17], zy = c.Y(100.15); return bgS() + `<rect x="24" y="${zy - 12}" width="272" height="20" rx="6" fill="${VI}" fill-opacity=".18" stroke="${VI}" stroke-opacity=".7" stroke-dasharray="5 4"/>` + c.svg + t.map((i, k) => dot(c.X(i), c.Y(100.15), VI, 3.8) + T(c.X(i), c.Y(100.15) - 14, String(k + 1), VI, 11, 800)).join('') + pill(160, 188, 'התנגדות: המחיר נעצר באזור הזה 3 פעמים', VI); },
  rr: () => bgS() + `<rect x="30" y="34" width="190" height="52" rx="6" fill="${GR}" fill-opacity=".15"/><rect x="30" y="86" width="190" height="34" rx="6" fill="${RD}" fill-opacity=".16"/>` + `<path d="M30 34H220" stroke="${GR}" stroke-width="2.4"/><path d="M30 86H220" stroke="${BL}" stroke-width="2.4"/><path d="M30 120H220" stroke="${RD}" stroke-width="2.4"/>` +
    pill(262, 34, 'יעד', GR) + pill(262, 86, 'כניסה', BL) + pill(262, 120, 'סטופ', RD) + T(125, 66, 'סיכוי', GR, 13, 800) + T(125, 108, 'סיכון', RD, 13, 800) + pill(125, 168, 'הרווח האפשרי כפול מההפסד האפשרי', '#fff', '#fff'),
  size: () => bgS() + `<rect x="24" y="64" width="272" height="30" rx="15" fill="#fff" fill-opacity=".08"/><rect x="24" y="64" width="31" height="30" rx="15" fill="${RD}" class="bar" style="transform-origin:24px 64px"/>` + T(160, 52, 'התיק: ‎5,000 ₪', '#fff', 14, 800) + pill(52, 112, '1% = 50 ₪', RD) + `<path d="M40 96v8" stroke="${RD}" stroke-width="1.6"/>` + [['מפסידים לכל היותר', '50 ₪', RD], ['קונים לפי הסטופ', 'לא לפי תחושה', GR]].map(([k, v, col], i) => `<g><rect x="${24 + i * 140}" y="134" width="132" height="46" rx="12" fill="#fff" fill-opacity=".06" stroke="#fff" stroke-opacity=".12"/>${T(90 + i * 140, 152, k, MUT, 10.5)}${T(90 + i * 140, 171, v, col, 14, 800)}</g>`).join('')
};
SCENES.candles = SCENES.riskline; SCENES.scale = SCENES.market; SCENES.coaster = SCENES.riskline;
const sceneSVG = (key) => { const f = SCENES[key] || SCENES.candle1; return `<svg direction="ltr" viewBox="0 0 320 200" preserveAspectRatio="xMidYMid meet" class="scene">${f()}</svg>`; };

/* onboarding hero scenes (portrait) */
function obScene(i) {
  const a = genC(90 + i, 30, 100, i === 1 ? .5 : .9, 3.4), c = chartBox(a, 10, 310, 120, 300, { delay: 150 }), id = uid(), g = uid();
  const pts = a.map((k, j) => `${c.X(j).toFixed(1)},${c.Y(k.c).toFixed(1)}`);
  let extra = '';
  if (i === 0) extra = `<g transform="translate(26 40)"><rect width="120" height="62" rx="16" fill="#fff" fill-opacity=".07" stroke="#fff" stroke-opacity=".16"/>${T(60, 24, 'שווי התיק', MUT, 11)}${T(60, 48, '₪5,000', '#fff', 20, 800)}</g><g transform="translate(176 66)"><rect width="118" height="50" rx="16" fill="${GR}" fill-opacity=".14" stroke="${GR}" stroke-opacity=".6"/>${T(59, 31, '+2.4%', GR, 19, 800)}</g>`;
  if (i === 1) { const y1 = c.Y(a[8].l), y2 = c.Y(a[8].l) + 18, y3 = c.Y(a[26].h) - 6; extra = `<rect x="10" y="${y1 - 4}" width="300" height="14" fill="${GD}" fill-opacity=".14"/>${dash(10, y1 + 3, 310, y1 + 3, GD)}${dash(10, y2 + 8, 310, y2 + 8, RD)}${dash(10, y3, 310, y3, GR)}${pill(54, y1 - 14, 'תמיכה', GD)}${pill(54, y2 + 22, 'סטופ', RD)}${pill(54, y3 - 14, 'יעד', GR)}`; }
  if (i === 2) extra = `<g transform="translate(160 78)"><circle r="40" fill="none" stroke="#fff" stroke-opacity=".12" stroke-width="12"/><circle r="40" fill="none" stroke="${GR}" stroke-width="12" stroke-dasharray="120 252" transform="rotate(-90)" class="seg"/><circle r="40" fill="none" stroke="${BL}" stroke-width="12" stroke-dasharray="60 252" stroke-dashoffset="-124" transform="rotate(-90)"/>${T(0, 6, '₪5,000', '#fff', 17, 800)}</g>`;
  return `<svg direction="ltr" viewBox="0 0 320 380" preserveAspectRatio="xMidYMid slice" class="scene"><defs><linearGradient id="${id}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#0d1424"/><stop offset="1" stop-color="#1b2347"/></linearGradient><radialGradient id="${g}" cx=".8" cy=".2" r=".8"><stop offset="0" stop-color="${i === 1 ? VI : GR}" stop-opacity=".3"/><stop offset="1" stop-opacity="0"/></radialGradient></defs><rect width="320" height="380" fill="url(#${id})"/><rect width="320" height="380" fill="url(#${g})"/><g stroke="#fff" stroke-opacity=".05">${[100, 160, 220, 280, 340].map(y => `<path d="M0 ${y}H320"/>`).join('')}</g>${c.svg}<path d="M${pts.join(' L')}" fill="none" stroke="${GR}" stroke-width="2.4" stroke-opacity=".65" stroke-linejoin="round" class="draw" style="filter:drop-shadow(0 0 8px ${GR})"/>${extra}${dot(c.X(29), c.Y(a[29].c), GR, 5)}</svg>`;
}

/* ----- small interactive toys inside lessons ----- */
const DEPTH = [78, 66, 54, 42, 32, 22];
function depthBars(b) { let s = ''; DEPTH.forEach((w, i) => { const y = 14 + i * 15, bw = Math.max(6, w * (1 + .16 * b)), sw = Math.max(6, (92 - w) * (1 - .16 * b)); s += `<rect x="${150 - bw * 1.6}" y="${y}" width="${bw * 1.6}" height="10" rx="5" fill="${GR}" fill-opacity="${.9 - i * .1}"/><rect x="154" y="${y}" width="${sw * 1.6}" height="10" rx="5" fill="${RD}" fill-opacity="${.4 + i * .08}"/>`; }); return s; }
function toyHTML(x) {
  if (x === 'scale') return `<div class="toy" id="toy"><svg direction="ltr" viewBox="0 0 304 110" class="toysvg"><g id="bars">${depthBars(0)}</g><path d="M152 6V104" stroke="#fff" stroke-opacity=".5" stroke-dasharray="3 4"/>${T(60, 106, 'קונים', GR, 11, 700)}${T(244, 106, 'מוכרים', RD, 11, 700)}</svg><div class="toy-p">מחיר: <b id="tp">100</b></div><div class="toy-b"><button class="chip" data-d="1">עוד קונים</button><button class="chip" data-d="-1">עוד מוכרים</button></div></div>`;
  if (x === 'flip') return `<div class="toy" id="toy"><svg direction="ltr" viewBox="0 0 304 90" class="toysvg" id="fl"></svg><div class="toy-p" id="tt"></div><div class="toy-b"><button class="chip on" data-d="up">יום ירוק</button><button class="chip" data-d="down">יום אדום</button></div></div>`;
  return '';
}
function bindToy(x, root) {
  const t = $('#toy', root); if (!t) return;
  if (x === 'scale') { let b = 0; t.onclick = (e) => { const c = e.target.closest('.chip'); if (!c) return; b = clamp(b + +c.dataset.d, -4, 4); $('#bars', t).innerHTML = depthBars(b); const p = $('#tp', t); p.textContent = 100 + b * 3; p.className = b >= 0 ? 'up' : 'down'; burst(e.clientX, e.clientY, c.dataset.d > 0 ? GR : RD, 6); }; }
  if (x === 'flip') {
    const paint = (up) => { const col = up ? GR : RD, y1 = up ? 60 : 24, y2 = up ? 24 : 60; $('#fl', t).innerHTML = `<line x1="152" x2="152" y1="8" y2="84" stroke="${col}" stroke-width="3" stroke-linecap="round"/><rect x="134" y="22" width="36" height="46" rx="6" fill="${col}"/>` + pill(80, up ? 66 : 28, 'פתיחה 100', MUT, '#c9cfd8') + pill(224, up ? 28 : 66, up ? 'סגירה 108' : 'סגירה 92', col) + dash(170, up ? 28 : 66, 190, up ? 28 : 66, col, 1) + dash(114, up ? 66 : 28, 134, up ? 66 : 28, MUT, 1); $('#tt', t).innerHTML = up ? 'נגמר גבוה ממה שהתחיל: <b class="up">נר ירוק</b>' : 'נגמר נמוך ממה שהתחיל: <b class="down">נר אדום</b>'; };
    paint(true);
    t.onclick = (e) => { const c = e.target.closest('.chip'); if (!c) return; $$('.chip', t).forEach(k => k.classList.toggle('on', k === c)); paint(c.dataset.d === 'up'); burst(e.clientX, e.clientY, c.dataset.d === 'up' ? GR : RD, 6); };
  }
}

/* ----- tap particles ----- */
function burst(x, y, color = GR, n = 10) {
  if (reduceMotion) return;
  const ph = $('#phone').getBoundingClientRect();
  for (let i = 0; i < n; i++) {
    const s = document.createElement('i'); s.className = 'spk';
    const a = Math.PI * 2 * i / n + Math.random() * .6, d = 22 + Math.random() * 22;
    s.style.cssText = `left:${x - ph.left}px;top:${y - ph.top}px;background:${color};--dx:${Math.cos(a) * d}px;--dy:${Math.sin(a) * d}px`;
    $('#phone').appendChild(s); setTimeout(() => s.remove(), 700);
  }
}
document.addEventListener('pointerdown', (e) => { const b = e.target.closest('.btn.primary,.opt,.rk,.chip,.tab'); if (b) burst(e.clientX, e.clientY, GR, 5); });

/* one-line note under each slide */
const SAY = {
  l1: ['מניה היא בעלות חלקית, לא כרטיס הגרלה.', 'המחיר נקבע בין קונים ומוכרים.', 'לחצו על הכפתורים וראו איך העומק משתנה.', 'ההפסד האפשרי הוא חלק מהמשחק.', 'אין סגנון נכון לכולם.'],
  l2: ['נר אחד מספר על פרק זמן אחד.', 'לחצו על הכפתורים כדי להחליף ביום ירוק או אדום.', 'הקווים הדקים מראים את מה שקרה באמצע.', 'הרבה נרות יחד נותנים תמונה.'],
  l3: ['מדד הוא תמונה כללית של השוק.', 'נפח גבוה אומר שהרבה אנשים פעלו.', 'הקו מחליק רעש ומראה כיוון.', 'תנודתיות היא גם סיכוי וגם סיכון.'],
  l4: ['מסתכלים על הנקודות הנמוכות, לא על נר אחד.', 'כל נקודה נמוכה גבוהה מהקודמת: מגמה עולה.', 'כל נקודה גבוהה נמוכה מהקודמת: מגמה יורדת.', 'קו ישר בין הנקודות מראה את הכיוון. תנסו בעצמכם בשוק.', 'כשאין כיוון, אין חובה לפעול.'],
  l5: ['המחיר עצר פעמיים או שלוש במקום דומה.', 'מחפשים נגיעות חוזרות באותו אזור.', 'אזור, לא מספר מדויק.', 'אזור יכול להישבר. מתכננים לזה.'],
  l6: ['התנגדות היא תקרה שהמחיר מתקשה לעבור.', 'מסמנים את הנגיעות החוזרות.', 'גם תקרה יכולה להישבר.'],
  l7: ['שלושה מספרים שמחליטים לפני העסקה.', 'כניסה עם סיבה, לא עם תחושה.', 'הסטופ הוא תנאי היציאה אם טועים.', 'היעד הוא תנאי היציאה אם צודקים.', 'כאן חושבים, לא מנחשים.'],
  l8: ['משווים את הרווח האפשרי להפסד האפשרי.', 'הרווח האפשרי כפול מההפסד האפשרי: יחס 1 ל-2.', 'גם תוכנית טובה מפסידה לפעמים.'],
  l9: ['קודם הסכום שמוכנים להפסיד, אחר כך גודל העסקה.', 'חישוב קצר מחליף את התחושה.', 'פיזור מקטין סיכון אבל לא מבטל אותו.', 'לפעמים ההחלטה הנכונה היא לחכות.']
};
